### ISSUE TITLE
Digest value definition

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-fft-rats-eat-measured-component#2]
I don't think the digest value should be restricted to things in memory or to start up time.

Seems like this could be used for RTIC (Run Time Integrity Check) which is something that can get run before every transaction or such.

Also, you might want to measure parts of the file system, registers or other.

**Comment by thomas-fossati** [comment]
Good point.

I am not against expanding applicability.  That said, the one concern I have is whether `tstr` is sufficient to carry *all* possible component identifiers.

**Comment by laurencelundblade** [comment]
I'm personally OK with tstr for the name. Keep it simple until there's a reason to do more.

Mostly, I'm interested in rewording so that it can be used for RTIC and other than the traditional measured boot.
