### ISSUE TITLE
Signing seems underspecified

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-fft-rats-eat-measured-component#4]
ckt is just a key ID, right? If you want signing, you need to bring in COSE like CoSWID does.

Also seems like a bit of a challenge to all support JOSE / JWS.

**Comment by thomas-fossati** [comment]
Closing this based on https://github.com/thomas-fossati/draft-fft-rats-eat-measured-component/issues/3#issuecomment-2021416501
